#ifndef GUARD_CONSTANTS_BERRY_H
#define GUARD_CONSTANTS_BERRY_H

#define BERRY_NONE 0

#define BERRY_FIRMNESS_UNKNOWN     0
#define BERRY_FIRMNESS_VERY_SOFT   1
#define BERRY_FIRMNESS_SOFT        2
#define BERRY_FIRMNESS_HARD        3
#define BERRY_FIRMNESS_VERY_HARD   4
#define BERRY_FIRMNESS_SUPER_HARD  5

#define BERRY_COLOR_RED    0
#define BERRY_COLOR_BLUE   1
#define BERRY_COLOR_PURPLE 2
#define BERRY_COLOR_GREEN  3
#define BERRY_COLOR_YELLOW 4
#define BERRY_COLOR_PINK   5

#define FLAVOR_SPICY   0
#define FLAVOR_DRY     1
#define FLAVOR_SWEET   2
#define FLAVOR_BITTER  3
#define FLAVOR_SOUR    4
#define FLAVOR_COUNT   5

#define BERRY_STAGE_NO_BERRY    0  // there is no tree planted and the soil is completely flat.
#define BERRY_STAGE_PLANTED     1
#define BERRY_STAGE_SPROUTED    2
#define BERRY_STAGE_TALLER      3
#define BERRY_STAGE_FLOWERING   4
#define BERRY_STAGE_BERRIES     5
#define BERRY_STAGE_TRUNK       6 // These follow BERRY_STAGE_BERRIES to preserve save compatibility
#define BERRY_STAGE_BUDDING     7
#define BERRY_STAGE_SPARKLING   255

// Berries can be watered in the following stages:
// - BERRY_STAGE_PLANTED
// - BERRY_STAGE_SPROUTED
// - BERRY_STAGE_TALLER
// - BERRY_STAGE_FLOWERING
#define NUM_WATER_STAGES 4

// IDs for berry tree objects, indexes into berryTrees in SaveBlock1
// Named for whatever berry is initially planted there on a new game
// Those with no initial berry are named "soil"
#define BERRY_TREE_ROUTE_3_ORAN_1    1
#define BERRY_TREE_ROUTE_3_ORAN_2     2
#define BERRY_TREE_ROUTE_104_SOIL_1   3 // SOIL
#define BERRY_TREE_ROUTE_2_PECHA_1   4
#define BERRY_TREE_ROUTE_2_PECHA_2  5
#define BERRY_TREE_ROUTE_4_ORAN    6
#define BERRY_TREE_ROUTE_4_PECHA  7
#define BERRY_TREE_ROUTE_4_CHERI  8
#define BERRY_TREE_ROUTE_104_SOIL_2   9 // SOIL
#define BERRY_TREE_ROUTE_5_CHESTO    10
#define BERRY_TREE_ROUTE_5_CHERI   11
#define BERRY_TREE_ROUTE_104_SOIL_3   12 // SOIL
#define BERRY_TREE_ROUTE_6_PECHA    13
#define BERRY_TREE_ROUTE_6_PERSIM 14
#define BERRY_TREE_ROUTE_6_ORAN  15
#define BERRY_TREE_ROUTE_6_LEPPA  16
#define BERRY_TREE_ROUTE_6_RAWST  17
#define BERRY_TREE_ROUTE_7_LIECHI  18
#define BERRY_TREE_ROUTE_7_PETAYA   19
#define BERRY_TREE_ROUTE_7_GANLON   20
#define BERRY_TREE_ROUTE_7_SALAC  21
#define BERRY_TREE_ROUTE_7_APICOT  22
#define BERRY_TREE_ROUTE_7_STARF  23
#define BERRY_TREE_ROUTE_7_PECHA  24
#define BERRY_TREE_ROUTE_7_CHESTO  25
#define BERRY_TREE_ROUTE_7_CHERI 26
#define BERRY_TREE_ROUTE_7_ORAN 27
#define BERRY_TREE_ROUTE_7_PERSIM 28
#define BERRY_TREE_ROUTE_7_ASPEAR 29
#define BERRY_TREE_ROUTE_9_SOIL_1  30
#define BERRY_TREE_ROUTE_9_SOIL_2 31
#define BERRY_TREE_ROUTE_9_SOIL_3     32
#define BERRY_TREE_ROUTE_9_SOIL_4 33
#define BERRY_TREE_ROUTE_9_SOIL_5  34
#define BERRY_TREE_ROUTE_9_SOIL_6  35
#define BERRY_TREE_ROUTE_9_SOIL_7  36
#define BERRY_TREE_ROUTE_9_SOIL_8 37
#define BERRY_TREE_ROUTE_9_SOIL_9 38
#define BERRY_TREE_ROUTE_9_SOIL_10 39
#define BERRY_TREE_ROUTE_9_SOIL_11  40
#define BERRY_TREE_ROUTE_9_SOIL_12  41
#define BERRY_TREE_ROUTE_9_SOIL_13  42
#define BERRY_TREE_ROUTE_9_SOIL_14     43
#define BERRY_TREE_ROUTE_9_KEE_1    44
#define BERRY_TREE_ROUTE_9_MARANGA_1    45
#define BERRY_TREE_ROUTE_9_LEPPA_1   46
#define BERRY_TREE_ROUTE_9_RAWST_1   47
#define BERRY_TREE_ROUTE_9_CHERI_1   48
#define BERRY_TREE_ROUTE_9_CHESTO_1    49
#define BERRY_TREE_ROUTE_9_CHILAN   50
#define BERRY_TREE_ROUTE_121_SOIL_1   51 // SOIL
#define BERRY_TREE_ROUTE_9_WACAN  52
#define BERRY_TREE_ROUTE_9_BABIRI  53
#define BERRY_TREE_ROUTE_121_SOIL_2   54 // SOIL
#define BERRY_TREE_ROUTE_11_OCCA   55
#define BERRY_TREE_ROUTE_11_PASSHO   56
#define BERRY_TREE_UNUSED             57 // UNUSED
#define BERRY_TREE_ROUTE_13_CHARTI  58
#define BERRY_TREE_ROUTE_13_SHUCA  59
#define BERRY_TREE_ROUTE_15_ASPEAR  60
#define BERRY_TREE_ROUTE_15_RAWST  61
#define BERRY_TREE_ROUTE_15_YACHE  62
#define BERRY_TREE_ROUTE_123_SOIL     63 // SOIL
#define BERRY_TREE_ROUTE_15_MICLE  64
#define BERRY_TREE_ROUTE_16_LIECHI  65
#define BERRY_TREE_ROUTE_16_PETAYA 66
#define BERRY_TREE_ROUTE_16_SALAC  67
#define BERRY_TREE_ROUTE_16_KEBIA 68
#define BERRY_TREE_ROUTE_16_COLBUR 69
#define BERRY_TREE_ROUTE_17_SITRUS_1 70
#define BERRY_TREE_ROUTE_17_SITRUS_2 71
#define BERRY_TREE_ROUTE_17_PAYAPA  72
#define BERRY_TREE_ROUTE_17_TANGA 73
#define BERRY_TREE_ROUTE_20_CHOPLE 74
#define BERRY_TREE_ROUTE_104_SOIL_4   75 // SOIL
#define BERRY_TREE_ROUTE_20_LUM  76
#define BERRY_TREE_ROUTE_20_ROSELI 77
#define BERRY_TREE_ROUTE_9_KEE_2 78
#define BERRY_TREE_ROUTE_9_MARANGA_2 79
#define BERRY_TREE_ROUTE_9_LEPPA_2   80
#define BERRY_TREE_ROUTE_9_RAWST_2   81
#define BERRY_TREE_ROUTE_9_CHERI_2   82
#define BERRY_TREE_ROUTE_9_CHESTO_2 83
#define BERRY_TREE_ROUTE_119_HONDEW_2 84
#define BERRY_TREE_ROUTE_119_SITRUS   85
#define BERRY_TREE_ROUTE_119_LEPPA    86
#define BERRY_TREE_ROUTE_123_PECHA    87
#define BERRY_TREE_ROUTE_123_SITRUS   88
#define BERRY_TREE_ROUTE_123_RAWST    89


// Remainder are unused

#define BERRY_TREES_COUNT 128

#endif // GUARD_CONSTANTS_BERRY_H
