Route4_MapScripts::
	.byte 0

Route4_EventScript_Anton::
	trainerbattle_single TRAINER_ANTON, Route4_Text_AntonIntro, Route4_Text_AntonDefeat
	msgbox Route4_Text_AntonPostBattle, MSGBOX_AUTOCLOSE
	end

Route4_EventScript_Alison::
	trainerbattle_single TRAINER_ALISON, Route4_Text_AlisonIntro, Route4_Text_AlisonDefeat
	msgbox Route4_Text_AlisonPostBattle, MSGBOX_AUTOCLOSE
	end

Route4_EventScript_Markus::
	trainerbattle_single TRAINER_MARKUS, Route4_Text_MarkusIntro, Route4_Text_MarkusDefeat
	msgbox Route4_Text_MarkusPostBattle, MSGBOX_AUTOCLOSE
	end

Route4_EventScript_Kevin::
	trainerbattle_single TRAINER_KEVIN, Route4_Text_KevinIntro, Route4_Text_KevinDefeat
	msgbox Route4_Text_KevinPostBattle, MSGBOX_AUTOCLOSE
	end

Route4_EventScript_Isidro::
	trainerbattle_single TRAINER_ISIDRO, Route4_Text_IsidroIntro, Route4_Text_IsidroDefeat
	msgbox Route4_Text_IsidroPostBattle, MSGBOX_AUTOCLOSE
	end

Route4_EventScript_Rick::
	trainerbattle_single TRAINER_RICK, Route4_Text_RickIntro, Route4_Text_RickDefeat
	msgbox Route4_Text_RickPostBattle, MSGBOX_AUTOCLOSE
	end

Route4_EventScript_Patrick::
	trainerbattle_single TRAINER_PATRICK, Route4_Text_PatrickIntro, Route4_Text_PatrickDefeat
	msgbox Route4_Text_PatrickPostBattle, MSGBOX_AUTOCLOSE
	end

Route4_EventScript_Deon::
	trainerbattle_single TRAINER_DEON, Route4_Text_DeonIntro, Route4_Text_DeonDefeat
	msgbox Route4_Text_DeonPostBattle, MSGBOX_AUTOCLOSE
	end

Route4_EventScript_Monte::
	trainerbattle_single TRAINER_MONTE, Route4_Text_MonteIntro, Route4_Text_MonteDefeat
	msgbox Route4_Text_MontePostBattle, MSGBOX_AUTOCLOSE
	end

Route4_EventScript_Melba::
	trainerbattle_single TRAINER_MELBA, Route4_Text_MelbaIntro, Route4_Text_MelbaDefeat
	msgbox Route4_Text_MelbaPostBattle, MSGBOX_AUTOCLOSE
	end

Route4_EventScript_Luther::
	trainerbattle_single TRAINER_LUTHER, Route4_Text_LutherIntro, Route4_Text_LutherDefeat
	msgbox Route4_Text_LutherPostBattle, MSGBOX_AUTOCLOSE
	end
