Route6_MapScripts::
	.byte 0

Route6_EventScript_Jeff::
	trainerbattle_single TRAINER_JEFF, Route6_Text_JeffIntro, Route6_Text_JeffDefeat
	msgbox Route6_Text_JeffPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Jacinto::
	trainerbattle_single TRAINER_JACINTO, Route6_Text_JacintoIntro, Route6_Text_JacintoDefeat
	msgbox Route6_Text_JacintoPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Rochelle::
	trainerbattle_single TRAINER_ROCHELLE, Route6_Text_RochelleIntro, Route6_Text_RochelleDefeat
	msgbox Route6_Text_RochellePostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Sherri::
	trainerbattle_single TRAINER_SHERRI, Route6_Text_SherriIntro, Route6_Text_SherriDefeat
	msgbox Route6_Text_SherriPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Greg::
	trainerbattle_single TRAINER_GREG, Route6_Text_GregIntro, Route6_Text_GregDefeat
	msgbox Route6_Text_GregPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Fred::
	trainerbattle_single TRAINER_FRED, Route6_Text_FredIntro, Route6_Text_FredDefeat
	msgbox Route6_Text_FredPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Clayton::
	trainerbattle_single TRAINER_CLAYTON, Route6_Text_ClaytonIntro, Route6_Text_ClaytonDefeat
	msgbox Route6_Text_ClaytonPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Marion::
	trainerbattle_single TRAINER_MARION, Route6_Text_MarionIntro, Route6_Text_MarionDefeat
	msgbox Route6_Text_MarionPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Chase::
	trainerbattle_single TRAINER_CHASE, Route6_Text_ChaseIntro, Route6_Text_ChaseDefeat
	msgbox Route6_Text_ChasePostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Carlene::
	trainerbattle_single TRAINER_CARLENE, Route6_Text_CarleneIntro, Route6_Text_CarleneDefeat
	msgbox Route6_Text_CarlenePostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Carlton::
	trainerbattle_single TRAINER_CARLTON, Route6_Text_CarltonIntro, Route6_Text_CarltonDefeat
	msgbox Route6_Text_CarltonPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Arnoldo::
	trainerbattle_single TRAINER_ARNOLDO, Route6_Text_ArnoldoIntro, Route6_Text_ArnoldoDefeat
	msgbox Route6_Text_ArnoldoPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Rashad::
	trainerbattle_single TRAINER_RASHAD, Route6_Text_RashadIntro, Route6_Text_RashadDefeat
	msgbox Route6_Text_RashadPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Ginger::
	trainerbattle_single TRAINER_GINGER, Route6_Text_GingerIntro, Route6_Text_GingerDefeat
	msgbox Route6_Text_GingerPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Lincoln::
	trainerbattle_single TRAINER_LINCOLN, Route6_Text_LincolnIntro, Route6_Text_LincolnDefeat
	msgbox Route6_Text_LincolnPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Roger::
	trainerbattle_single TRAINER_ROGER, Route6_Text_RogerIntro, Route6_Text_RogerDefeat
	msgbox Route6_Text_RogerPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Timothy::
	trainerbattle_single TRAINER_TIMOTHY, Route6_Text_TimothyIntro, Route6_Text_TimothyDefeat
	msgbox Route6_Text_TimothyPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Kelly::
	trainerbattle_single TRAINER_KELLY, Route6_Text_KellyIntro, Route6_Text_KellyDefeat
	msgbox Route6_Text_KellyPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Jewel::
	trainerbattle_single TRAINER_JEWEL, Route6_Text_JewelIntro, Route6_Text_JewelDefeat
	msgbox Route6_Text_JewelPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Darnell::
	trainerbattle_single TRAINER_DARNELL, Route6_Text_DarnellIntro, Route6_Text_DarnellDefeat
	msgbox Route6_Text_DarnellPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Mauro::
	trainerbattle_single TRAINER_MAURO, Route6_Text_MauroIntro, Route6_Text_MauroDefeat
	msgbox Route6_Text_MauroPostBattle, MSGBOX_AUTOCLOSE
	end

Route6_EventScript_Newton::
	trainerbattle_single TRAINER_NEWTON, Route6_Text_NewtonIntro, Route6_Text_NewtonDefeat
	msgbox Route6_Text_NewtonPostBattle, MSGBOX_AUTOCLOSE
	end
